version: '3'

services:

  strava_api:
    image: strava_api
    container_name: strava_api
    restart: always
    build: ./strava_api
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
